---
title: "Final Project"
author: "Tanner Gildea"
date: "4/2/2019"
output: html_document
---

```{r setup, include=FALSE}
library(twitteR)
library(dplyr)
library(ggplot2)
library(tidyverse)

# Access keys from developer app. 
consumer_key <- "JiBgIY3c2oSYaluzC9901ZpGH"
consumer_secret <- "T0cbKHAWJe6NW3e24F8KvvFeV6lv54aeNmavAGFyL9qHVFm7tL"
access_token <- "1091061777935355905-pd7WDjnoiOSxcEKMgxyucfOLHtOhk4"
access_secret <- "nLgDpWG4FhhbAvTGLeEET1nXkAkbVmMw08uZEmin54sRS"

# This section will actually conduct the download.

setup_twitter_oauth(
    consumer_key, consumer_secret, access_token, access_secret)

harris <- userTimeline("KamalaHarris", n = 3200, includeRts=T)

# To change from a list into a dataframe.
df.harris <- twListToDF(harris)


tweets <- bind_rows(
  df.harris %>% filter(isRetweet==F) %>%
    select(
      text, screenName, created, retweetCount, favoriteCount))

```
# The Data

Instructive guide for accessing, downloading, and manipulating Twitter data using the twitteR package: https://medium.com/the-artificial-impostor/analyzing-tweets-with-r-92ff2ef990c6



# Visualization

```{r}


```

